---
pagetitle: "Events"
output: 
  html_document:
    css: ["../css/style.css"]
    includes:
        in_header: ../addons/analytics.html
        before_body: ../addons/_navbar_custom.html
    theme: flatly
---


```{css, echo=FALSE}

.container{
  margin-left: 5px;
  margin-right: 5px;
  max-width: 1200px;
}

.col-1, .col-2{
  width: 40%;
  display: inline-block;
  vertical-align: top;
  margin-right:20px;
  margin-left:20px;
}

@media only screen and (max-width: 900px) {
  /* For mobile phones: */
  [class*="col-"] {
    width: 100%;
  }
}

```

<br>
<font size = 3> 

I love public speaking, and would be glad to join you at your event. To see more information about my areas of expertise and requirements for participation, please visit <a href="booking.html" onclick="gtag('event', 'click', {'event_category' : 'internal', 'event_action' : 'internalclick', 'event_label' : 'booking'});" >my bookings page</a>.

<BR>

## Upcoming Appearances 

<BR>

Available for future talks- get in touch!

<BR>



### Past Appearances 

If you have any questions about any of the talks below, contact me on twitter! 

<BR>

<div class= "container">
<div class="col-1">
#### Event: Gartner Supply Chain Symposium/Xpo 2023   

Topic: Maximize Productivity with Shipment Data & ML-Driven Smart Geofences   
Location: Orlando, FL  
Date: May 9, 2023  
Co-presented with Nick Clark   
Links: <a href="https://explore.project44.com/et0/en-gartner-symposium-2023" onclick="gtag('event', 'click', {'event_category' : 'conftalk', 'event_action' : 'outclick', 'event_label' : 'gartner'}); ">https://explore.project44.com/et0/en-gartner-symposium-2023</a> 
<BR>
<BR>
</div>

<div class="col-1">
#### Event: MLOps Community Meetup - Chicago   

Topic: Generating "Smart" Geofences with Clustering Techniques     
Location: Chicago Loop, Toast offices  
Date: November 10, 2022    
Links: <a href="https://mlops.community" onclick="gtag('event', 'click', {'event_category' : 'conftalk', 'event_action' : 'outclick', 'event_label' : 'mlops'}); ">https://mlops.community</a> 
<BR>
<BR>
</div>
<div class="col-2">

#### Event: VisInPractice @ IEEE VIS 2021

Topic: Virtual Panel on Visualization Tool Ecosystems  
Location: Virtual  
Date: October 25, 2021    
Links: <a href="http://ieeevis.org/year/2021/info/visinpractice" onclick="gtag('event', 'click', {'event_category' : 'conftalk', 'event_action' : 'outclick', 'event_label' : 'visinpractice'}); ">http://ieeevis.org/year/2021/info/visinpractice</a>   
<a href="http://ieeevis.org/year/2021/welcome" onclick="gtag('event', 'click', {'event_category' : 'conftalk', 'event_action' : 'outclick', 'event_label' : 'ieee'}); ">http://ieeevis.org/year/2021/welcome</a>

<BR>
</div>

<div class="col-1">

#### Podcast: Beautiful Bastards Podcast   

Topic: Data Science/Machine Learning misc     
Location: Virtual  
Date: October 4, 2021    
Links: <a href="https://www.beautifulbastardspodcast.com/the-rise-of-ai-stephanie-kirmer-on-the-future-of-big-tech/" onclick="gtag('event', 'click', {'event_category' : 'citation', 'event_action' : 'outclick', 'event_label' : 'beautifulbastardspodcast'});">beautifulbastardspodcast.com</a> 

* The Chicago SSL: [Tribune](https://www.chicagotribune.com/news/criminal-justice/ct-chicago-police-strategic-subject-list-ended-20200125-spn4kjmrxrh4tmktdjckhtox4i-story.html) and [Chicago Magazine](https://www.chicagomag.com/city-life/August-2017/Chicago-Police-Strategic-Subject-List/)
* [Machine learning for kids book](https://www.amazon.com/dp/1732508003/ref=cm_sw_r_awdo_navT_a_ZGE410W6CNQF5W4ZNKXK)


<BR>

</div>


<div class="col-2">

#### Event: Center for Deep Learning Spring 2021 Seminar, Northwestern University   

Topic: Accelerating Deep Learning with Dask and GPUs     
Location: Virtual  
Date: April 27, 2021    
Links: <a href="https://www.mccormick.northwestern.edu/research/deep-learning/" onclick="gtag('event', 'click', {'event_category' : 'conftalk', 'event_action' : 'outclick', 'event_label' : 'cdl-nu'}); ">https://www.mccormick.northwestern.edu/research/deep-learning//</a>   
<a href="https://github.com/skirmer/gpu_pytorch/tree/main/center-deep-learning" onclick="gtag('event', 'click', {'event_category' : 'conftalk', 'event_action' : 'outclick', 'event_label' : 'cdl_gh'}); ">https://github.com/skirmer/gpu_pytorch/tree/main/center-deep-learning</a>

<br><BR>
</div>
</div>
<div class= "container">
<div class= "col-1"> 

#### Event: ODSC East 2021   

Topic: Going Beyond Matplotlib and Seaborn: A survey of Python data visualization tools     
Location: Virtual  
Date: March 29 - April 1 2021    
Links: <a href="https://odsc.com/boston/" onclick="gtag('event', 'click', {'event_category' : 'conftalk', 'event_action' : 'outclick', 'event_label' : 'odsc'}); ">https://odsc.com/boston/</a>   
<a href="https://github.com/skirmer/new-py-dataviz" onclick="gtag('event', 'click', {'event_category' : 'conftalk', 'event_action' : 'outclick', 'event_label' : 'odsc_gh'}); ">https://github.com/skirmer/new-py-dataviz</a>

<BR>
</div>
<div class="col-2">

#### Event: R Ladies Chicago - Workshop   

  Topic: Functions for R Programming Beginners     
  Location: Virtual  
  Date: February 26, 2021   
  Links:    
  <a href="https://rladieschicago.org/" onclick="gtag('event', 'click', {'event_category' : 'conftalk', 'event_action' : 'outclick', 'event_label' : 'rladies'}); ">https://rladieschicago.org/</a>   
  <a href="https://github.com/skirmer/functions_r" onclick="gtag('event', 'click', {'event_category' : 'conftalk', 'event_action' : 'outclick', 'event_label' : 'rfun_feb2021_gh'}); ">https://github.com/skirmer/functions_r</a>   
  Video: https://youtu.be/TCIMT6l53tQ 

<br><BR>
</div>
</div>
<div class= "container">
<div class= "col-1"> 


#### Event: Outlier Data Visualization Conference 2021   

  Topic: Going Beyond Matplotlib and Seaborn: A survey of Python data visualization tools     
  Location: Virtual  
  Date: February 7, 2021    
  Links: https://www.outlierconf.com/    
  https://github.com/skirmer/new-py-dataviz   

<BR>
</div>
<div class="col-2">


#### Event: RE*WORK's Deep Learning Virtual Summit, January 2021   

  Topic: Scaling Up PyTorch with GPU Cluster Computing  
  Location: Virtual  
  Date: January 28-29, 2021  
  Links: https://www.re-work.co/events/deep-learning-virtual-summit-2021/schedule   
  https://github.com/skirmer/gpu_pytorch  

<br><BR>
</div>
</div>
<div class= "container">
<div class= "col-1"> 

#### Event: R Ladies Dallas, December 2020   

  Topic: Branching Out into Isolation Forests: Tree Based Anomaly Detection    
  Location: Virtual  
  Date: December 7, 2020  
  Links: https://www.meetup.com/rladies-dallas/events/274004809/  
  https://github.com/skirmer/isolation_forests   
  Video to come

<BR>
</div>
<div class="col-2">

#### Event: ChiPy Data SIG October 2020   

  Topic: Branching Out into Isolation Forests: Tree Based Anomaly Detection    
  Location: Virtual  
  Date: October 21, 2020  
  [Video](https://youtu.be/hDK8lTeKR9Y?t=3847)  
  Links: https://www.chipy.org/    
  https://www.meetup.com/_ChiPy_/events/272525624/   

<br><BR>
</div>
</div>
<div class= "container">
<div class= "col-1"> 

#### Event: ODSC Europe Virtual Conference 2020   

  Topic: Making Happy Modelers: Build and Maintain Your Data Warehouse with AWS Redshift and Airflow    
  Location: Virtual  
  Date: September 17-19, 2020    
  Links: https://odsc.com/speakers/making-happy-modelers-build-and-maintain-your-data-warehouse-with-aws-redshift-and-airflow/

<BR>
</div>
<div class="col-2">

#### Event: RE*WORK's Virtual Applied AI Summit - Spring 2020   

  Topic: Moderator, Panel: Strategies for Effectively Building, Deploying, and Monitoring AI    
  Location: Virtual/London, UK   
  Date: May 21, 2020    
  Links: https://www.re-work.co/events/applied-ai-virtual-summit   

<br><BR>
</div>
</div>
<div class= "container">
<div class= "col-1"> 

#### Event: Women in Data Science Chicago 2020  
  Topic: Better Data Science Team Collaboration with R    
  Location: Chicago, IL   
  Date: March 6, 2020    
  Links: https://github.com/skirmer/team_collab 
  https://widschicago.org/  

<BR>
</div>
<div class="col-2">


#### Event: DC R Conference  
  Topic: Animation for Effective Data Visualization with R    
  Location: Washington, DC    
  Date: November 8, 2019  
  [Video](https://youtu.be/tfpa_QYHebQ)   
  Links: https://github.com/skirmer/animating_dataviz  
  https://dc.rstats.ai/2019/dcr/  

<br><BR>
</div>
</div>
<div class= "container">
<div class= "col-1"> 

#### Event: <a href="https://odsc.com/california/">ODSC West</a>  
  Topic: Elasticsearch End User Workflows in R and Python - Interactive Workshop   
  Location: San Francisco, CA  
  Date: November 1, 2019   
  Links: https://github.com/skirmer/elastic_analytics  

<BR>
</div>
<div class="col-2">


#### Event: R-Ladies Chicago and Chicago Data Visualization Community Joint Meetup  
  Topic: Animation for Effective Data Visualization with R   
  Location: Chicago, IL  
  Date: July 24, 2019  
  [Video](https://youtu.be/KWECmB0LUqU)    
  Links: https://github.com/skirmer/animating_dataviz    

<br><BR>
</div>
</div>
<div class= "container">
<div class= "col-1"> 

#### Event: REV 2  
  Topic: Elasticsearch End User Workflows in R and Python   
  Location: New York, NY  
  Date: May 23, 2019  
  [Video](https://dominodatalab.wistia.com/medias/i0f5by0f4q)  
  Links: https://github.com/skirmer/elastic_analytics    
  [Listen to my conversation with Eric Kavanagh on Inside Analytics podcast](https://insideanalysis.com/insights-from-domino-data-labs-2019-rev2-conference/)  

<BR>
</div>
<div class="col-2">


#### Event: satRday Chicago  
  Topic: Keynote: What Data Science Can Learn From Sociology  
  Location: Chicago, IL  
  Date: April 27, 2019   
  [Video](https://www.youtube.com/watch?v=quFhQvizBE8&feature=youtu.be&t=1095)    
  Links: https://github.com/skirmer/satRdays_chicago_2019  

<br><BR>
</div>
</div>
<div class= "container">
<div class= "col-1"> 

#### Event: R Package Building Workshop  
  Topic: 1 day seminar for women and nonbinary folks  
  Location: Chicago, IL  
  Date: February 23, 2019  
  Links: https://github.com/skirmer/r_packages  

<BR>
</div>
<div class="col-2">


#### Event: EARL Roadshow Seattle 2018  
  Topic: R Packages for Team Collaboration  
  Location: Seattle, WA  
  Date: November 7, 2018    
  Links: https://github.com/skirmer/team_collab 

<br><BR>
</div>
</div>
<div class= "container">
<div class= "col-1"> 

#### Event: ODSC East 2018  
  Topic: R Packages for Team Collaboration  
  Location: Boston, MA  
  Date: May 3, 2018    
  Links: https://github.com/skirmer/team_collab  

<BR>
</div>
<div class="col-2">


#### Event: Metis Speaker Series  
  Topic: R Packages for Team Collaboration  
  Location: Chicago, IL  
  Date: April 2018    
  Links: https://github.com/skirmer/team_collab  

<br><BR>
</div>
</div>
<div class= "container">
<div class= "col-1"> 

#### Partially Derivative Podcast   
  May 9, 2017   
  http://partiallyderivative.com/podcast/2017/05/09/data-science-near-you  
<br><BR>

</div>
</div>

</font>
<br><BR>
<font size = 2> [Looking for a speaker?](booking.html) Contact me at stephanie@stephaniekirmer.com. 


<BR>

<a href="http://www.kaggle.com/skirmer" onclick="gtag('event', 'click', {'event_category' : 'social', 'event_action' : 'outclick', 'event_label' : 'kaggle'});">kaggle</a>  | 
<a href="http://github.com/skirmer" onclick="gtag('event', 'click', {'event_category' : 'social', 'event_action' : 'outclick', 'event_label' : 'github'});">github</a> | 
<a href="http://linkedin.com/in/skirmer" onclick="gtag('event', 'click', {'event_category' : 'social', 'event_action' : 'outclick', 'event_label' : 'linkedin'});">linkedin</a> | 
<a href="https://youtube.com/playlist?list=PLxqXzy1mNUwclPONsSpw4Qa-pakNzpLva" onclick="gtag('event', 'click', {'event_category' : 'social', 'event_action' : 'outclick', 'event_label' : 'youtube'});">youtube</a> 

</font>
