---
pagetitle: "Projects"
output: 
  html_document:
    css: ["../css/style.css"]
    includes:
        in_header: ../addons/analytics.html
        before_body: ../addons/_navbar_custom.html
    theme: flatly
---


```{css, echo=FALSE}
.container{width:100%;
  }

.col-1, .col-2{
  width: 40%;
  display: inline-block;
  vertical-align: top;
  margin-right:20px;
  margin-left:20px;
}

@media only screen and (max-width: 900px) {
  /* For mobile phones: */
  [class*="col-"] {
    width: 100%;
  }
}

```

<BR>
<BR>


## Projects and Content
<BR>

#### <a href="https://medium.com/towards-data-science/what-does-it-mean-when-machine-learning-makes-a-mistake-37b213200697"  onclick="gtag('event', 'click', {'event_category' : 'citation', 'event_action' : 'outclick', 'event_label' : 'ml-mistakes'});">Article: Towards Data Science: "What Does It Mean When Machine Learning Makes a Mistake?"</a> 
What do we mean when we say that a model makes a mistake? In this article I discuss this question with attention to generative AI in particular.

*Keywords: ai, machine learning*

***

#### <a href="https://medium.com/towards-data-science/machine-learnings-public-perception-problem-48daf587e7a8"  onclick="gtag('event', 'click', {'event_category' : 'citation', 'event_action' : 'outclick', 'event_label' : 'public-per-ml'});">Article: Towards Data Science: "Machine Learning's Public Perception Problem"</a> 
In this piece, I take a close look at why the public doesn't have an accurate understanding of machine learning/AI, and explain what the negative results will be if data science doesn't work to fix this problem.

*Keywords: public policy, education, machine learning*

***


#### <a href="https://medium.com/towards-data-science/archetypes-of-the-data-scientist-role-1b078966fb2"  onclick="gtag('event', 'click', {'event_category' : 'citation', 'event_action' : 'outclick', 'event_label' : 'ds_archetypes'});">Article: Towards Data Science: "Archetypes of the Data Science Role"</a> 
A discussion of the different forms a data science job can take, including practical explanation of what the responsibilities look like. I also discuss the overloading of individual roles and how that can cause burnout.

*Keywords: data science, careers*

***



#### <a href="https://towardsdatascience.com/machine-learning-engineers-what-do-they-actually-do-e666081c3181"  onclick="gtag('event', 'click', {'event_category' : 'citation', 'event_action' : 'outclick', 'event_label' : 'mle_whatdotheydo'});">Article: Towards Data Science: "Machine Learning Engineers: What do they actually do?"</a> 
My thoughts on the evolution of job titles and career paths in the DS/ML field, including some discussion of the possible DEI implications.

*Keywords: dei, machine learning*

***

#### <a href="https://medium.com/project44-techblog/setting-healthy-boundaries-generating-geofences-at-scale-with-machine-learning-part-1-c2067ef49777"  onclick="gtag('event', 'click', {'event_category' : 'citation', 'event_action' : 'outclick', 'event_label' : 'smartgeo_pt1'});">Series: project44 Tech Blog: "Setting Healthy Boundaries: Generating Geofences at Scale with Machine Learning"</a> 

My step by step description of how I designed and implemented the Smart Geofences feature at project44.

<ul>
<li><a href="https://medium.com/project44-techblog/setting-healthy-boundaries-generating-geofences-at-scale-with-machine-learning-part-1-c2067ef49777"  onclick="gtag('event', 'click', {'event_category' : 'citation', 'event_action' : 'outclick', 'event_label' : 'smartgeo_pt1'});">Part 1</a>
</li>
<li><a href="https://medium.com/project44-techblog/setting-healthy-boundaries-generating-geofences-at-scale-with-machine-learning-part-2-eaa81b2d26d8"  onclick="gtag('event', 'click', {'event_category' : 'citation', 'event_action' : 'outclick', 'event_label' : 'smartgeo_pt2'});">Part 2</a>
</li>
</ul>

*Keywords: gis, geofences, machine learning, devops, airflow, python*

***

#### <a href="https://towardsdatascience.com/starting-a-new-machine-learning-model-beeb81a361b8"  onclick="gtag('event', 'click', {'event_category' : 'citation', 'event_action' : 'outclick', 'event_label' : 'mle_whatdotheydo'});">Article: Towards Data Science: "Starting a New Machine Learning Model"</a> 
In this article I described my process for starting a new ML project, and gave tips from my experience for newer data scientists.

*Keywords: machine learning, tutorial, advice*

***




#### <a href="https://www.beautifulbastardspodcast.com/the-rise-of-ai-stephanie-kirmer-on-the-future-of-big-tech/" onclick="gtag('event', 'click', {'event_category' : 'citation', 'event_action' : 'outclick', 'event_label' : 'beautifulbastardspodcast'});">Podcast: Appearance on "Beautiful Bastards Podcast"</a> 
The hosts of this show gave me an hour to talk about all kinds of issues in DS/ML, including ethics, data privacy, risk/rewards, D&I, and more. I mentioned a couple of things in the episode that are linked below.

* The Chicago SSL: [Tribune](https://www.chicagotribune.com/news/criminal-justice/ct-chicago-police-strategic-subject-list-ended-20200125-spn4kjmrxrh4tmktdjckhtox4i-story.html) and [Chicago Magazine](https://www.chicagomag.com/city-life/August-2017/Chicago-Police-Strategic-Subject-List/)
* [Machine learning for kids book](https://www.amazon.com/dp/1732508003/ref=cm_sw_r_awdo_navT_a_ZGE410W6CNQF5W4ZNKXK)

*Keywords: ethics, machine learning*  

***

#### [Series: Cloud Based Machine Learning Workflows](https://medium.com/@s.kirmer/machine-learning-development-in-the-cloud-part-1-e60920725af0)
<ul>
<li>[Part 1: Intro](https://medium.com/@s.kirmer/machine-learning-development-in-the-cloud-part-1-e60920725af0)</li>
<li>[Part 2: The IDE](https://medium.com/@s.kirmer/machine-learning-development-in-the-cloud-part-2-the-ide-dc912182e919)</li>
<li>[Part 3: Code](https://medium.com/codex/machine-learning-development-in-the-cloud-part-3-code-a568726c9dff)</li>
<li>[Part 4: Data](https://medium.com/codex/machine-learning-development-in-the-cloud-part-4-data-2437cadb5e38)</li>
<li>[Part 5: Images/Environments](https://medium.com/codex/machine-learning-development-in-the-cloud-part-5-environments-images-87e2b957debe)</li>
<li>[Part 6: Jobs & Automation](https://medium.com/codex/machine-learning-development-in-the-cloud-part-6-jobs-and-automation-2874dbd126b5)</li>
</ul>

In this series, I took a close look at these 5 areas of the data science or machine learning development workflow, telling you what the cloud approach looks like versus the local approach, explaining the pros and cons of each, and describing a few tools you might want to try.

*Keywords: python, machine learning, cloud computing*  

***

#### [Tutorial: Deploying ML Models - Flask or Voila, API or Web App!](https://medium.com/geekculture/deploy-your-machine-learning-model-with-flask-or-voila-c74a07921604)
Data science model deployment can sound intimidating if you have never had a chance to try it in a safe space. In this blog post, I give the end-to-end explanation of how you go from zero to a deployment that you can share with others.

*Keywords: python, HTML, machine learning, deployment, API*  

***

#### [Article: List Comprehensions in Python](https://python.plainenglish.io/list-comprehensions-in-python-c085fe9aa6f1)
List comprehensions are incredibly powerful, but also can be unintuitive and confusing. I wrote a guide to understanding and using them, designed for those who use for-loops in their regular programming.

*Keywords: python, programming, beginners*  

***

#### [Tutorial: Parallel GAN Training on GPU: Generate Your Own Images](https://medium.com/codex/parallel-gan-training-on-gpu-generate-your-own-images-9aa807042ef1)
Generative Adversarial Networks (GANs) are an increasingly popular and very powerful form of computer vision deep learning, and they require a whole lot of compute to be done effectively and speedily. This is just the sort of use case where parallelization with Dask clusters can make a difference in your workflow, so I wrote a tutorial on how to do it!

*Keywords: python, machine learning, deep learning, dask*  

***

#### [Article: Beyond Matplotlib and Seaborn: Python Data Visualization Tools That Work](https://medium.com/codex/beyond-matplotlib-and-seaborn-python-data-visualization-tools-that-work-3ef7f8d1500e)
I wrote a blogpost to accompany several talks and a github repo all about using different Python visualization tools. Get the code at https://github.com/skirmer/new-py-dataviz.

*Keywords: python, data visualization*  

***

#### [Article: Dask and pandas: There’s No Such Thing as Too Much Data](https://towardsdatascience.com/dask-and-pandas-theres-no-such-thing-as-too-much-data-284763348459)
Do you love pandas, but hate when you reach the limits of your memory or compute resources? Dask gives you the chance to use the pandas API with distributed data and computing. In this article, you’ll learn how it really works, how to use it yourself, and when/if to switch.

*Keywords: python, pandas, dask*  

***

#### [Article: Eager Data Scientist's Guide to Lazy Evaluation with Dask](https://towardsdatascience.com/guide-to-lazy-evaluation-with-dask-543b48a0aa74)
Lazy evaluation is the core of parallelization, but it doesn’t have to be confusing or complicated — in this guide, learn the basic concepts you need to get started! I use dask to demonstrate but this is useful for anyone trying to get the hang of parallel computation.
*Keywords: python, parallelization, dask*  

***

#### [Opinion: Your Data Scientist Does Not Need a STEM Ph.D.](https://towardsdatascience.com/your-data-scientist-does-not-need-a-stem-ph-d-7f2206f43871)
You should not require or ask for a generic STEM Ph.D. for data scientist candidates. In this blog post, I give a detailed argument on this and discuss the critiques of the practice.

*Keywords: data science, social science*  

***


#### [Tutorial: Combining Dask and PyTorch for Better, Faster Transfer Learning](https://medium.com/analytics-vidhya/combining-dask-and-pytorch-for-better-faster-transfer-learning-6ff64963e685)
I use the Stanford Dogs dataset again, this time to demonstrate accelerating transfer learning to improve Resnet50. The inner workings of how PyTorch supports multi-machine, multi-GPU training can be confusing but I have deciphered it for you here.

*Keywords: machine learning, python, deep learning*  

***

#### [Tutorial: Computer Vision at Scale with Dask and PyTorch](https://towardsdatascience.com/computer-vision-at-scale-with-dask-and-pytorch-a18e17fc5bad)
I use the Stanford Dogs dataset to demonstrate accelerating an image classification problem with GPU Clusters. If you have been thinking about GPUs but don't know where to start, or what they might be good for, I recommend this as a place to start!

*Keywords: machine learning, python, deep learning*  

***


#### [Article: 3 Ways to Schedule and Execute Python Jobs](https://www.saturncloud.io/s/job-scheduling-with-python/)
Job scheduling is what takes academic machine learning to production level for real business or project value. I went through three tools (cron, Airflow, and Prefect) in this article and discussed the pros and cons to each. Depending on your task and circumstances, any one of these tools might be what you need.

*Keywords: python, job scheduling, airflow*  


***

#### [Article: Make Your Data Move: Using Schedulers with Data Storage to Generate Business Value](https://opendatascience.com/make-your-data-move-using-schedulers-with-data-storage-to-generate-business-value/)
In concert with my presentation at ODSC Europe 2020 I wrote a blog post to discuss why and how you might use scheduled jobs to make your data infrastructure work better for modeling and machine learning. 

*Keywords: job scheduling, airflow, data warehousing*  



***

<div class="col-footer">
[See more projects](more_projects.html)

<font size = 2>

<BR>
stephanie@stephaniekirmer.com 
<BR> 

<a href="http://github.com/skirmer" onclick="gtag('event', 'click', {'event_category' : 'social', 'event_action' : 'outclick', 'event_label' : 'github'});" ><i class="fab fa-github fa-1x"></i></a>
|  <a href="http://linkedin.com/in/skirmer" onclick="gtag('event', 'click', {'event_category' : 'social', 'event_action' : 'outclick', 'event_label' : 'linkedin'});" ><i class="fab fa-linkedin fa-1x"></i></a> 
|  <a href="https://medium.com/@s.kirmer" onclick="gtag('event', 'click', {'event_category' : 'social', 'event_action' : 'outclick', 'event_label' : 'medium'});" ><i class="fab fa-medium fa-1x"></i></a><BR>

</font>
</div>
