---
pagetitle: "Events"
output: 
  html_document:
    includes:
        in_header: analytics.html
        before_body: _navbar.html
    theme: flatly
---


```{css, echo=FALSE}
body {
  color: black;
  margin-left: 50px;
  margin-right: 50px;
}

.header{

}

.navbar-brand {
    padding: 0 !important;
}
# .navbar-brand img {
#     border-right: 2px solid white;
#     height:51px;
# }
.navbar-text {
    color: white !important;
    font-weight: bold !important;
    margin-left:15px;
}

.nav, .navbar-nav, .navbar-right{
  padding-top:8px;
  padding-bottom:8px;
}

```


<BR>
<BR>
<BR>
</font>
<br>
<font size = 3> 

I love public speaking, and would be glad to join you at your event. 

<div style="border: .5px solid lightgrey; padding: 20px; margin-top:20px; margin-bottom:20px">
I believe that our personal values should be reflected in our work, so I don't participate in events where I am the only woman, events with one or fewer people of color on the speaking schedule, or events organized by groups that don't explicitly support equal opportunity and require respectful conduct from attendees. 

There is an abundance of extremely talented women, people of color, and LGBT+ people in the data science industry, and if you are struggling to find them for your event or job opening, please let me know and I may be able to help connect you.

</div>

That said, if you're looking for a speaker, contact me at stephanie@stephaniekirmer.com or visit [my SpeakerHub profile](https://speakerhub.com/speaker/stephanie-kirmer).


I'm available to speak on the following topics:  

* Machine learning production workflows using AWS Redshift and Airflow  
* Applications of machine learning in hospitality industry or IIOT   
* Sociological insights on data science, machine learning, and/or AI  
* Data visualization with R (including animation, network graphs, and maps/GIS)  
* Data storage in AWS Redshift   
* Data storage in Elasticsearch    
* Using Elasticsearch for analytics end users  
* R package development  
* Collaboration across teams with R or Python libraries  

Or other topics - please contact me if something adjacent would fit your audience! 

<BR>
<BR>

</font>

## Upcoming Appearances 

<BR>
<font size = 4>
</font>
<B>Up next:</b>  


#### Event: ChiPy Data SIG October 2020   

Topic: Branching Out into Isolation Forests: Tree Based Anomaly Detection    
Location: Virtual  
Date: October 21, 2020  
Links: https://www.chipy.org/    
https://www.meetup.com/_ChiPy_/events/272525624/   
There will be a free livestream on YouTube, so please join!

<BR>
<BR>

### Past Appearances 

If you have any questions about any of the talks below, contact me on twitter! 

<BR>

#### Event: ODSC Europe Virtual Conference 2020   

Topic: Making Happy Modelers: Build and Maintain Your Data Warehouse with AWS Redshift and Airflow    
Location: Virtual  
Date: September 17-19, 2020    
Links: https://odsc.com/speakers/making-happy-modelers-build-and-maintain-your-data-warehouse-with-aws-redshift-and-airflow/


<BR>

#### Event: RE*WORK's Virtual Applied AI Summit - Spring 2020   

Topic: Moderator, Panel: Strategies for Effectively Building, Deploying, and Monitoring AI    
Location: Virtual/London, UK   
Date: May 21, 2020    
Links: https://www.re-work.co/events/applied-ai-virtual-summit   

<BR>

#### Event: Women in Data Science Chicago 2020  
Topic: Better Data Science Team Collaboration with R    
Location: Chicago, IL   
Date: March 6, 2020    
Links: https://github.com/skirmer/team_collab 
https://widschicago.org/  

<BR>


#### Event: DC R Conference  
Topic: Animation for Effective Data Visualization with R    
Location: Washington, DC    
Date: November 8, 2019  
[Video](https://youtu.be/tfpa_QYHebQ)   
Links: https://github.com/skirmer/animating_dataviz  
https://dc.rstats.ai/2019/dcr/  

<BR>

#### Event: <a href="https://odsc.com/california/">ODSC West</a>  
Topic: Elasticsearch End User Workflows in R and Python - Interactive Workshop   
Location: San Francisco, CA  
Date: November 1, 2019   
Video: Coming Soon  
Links: https://github.com/skirmer/elastic_analytics  

<BR>

#### Event: R-Ladies Chicago and Chicago Data Visualization Community Joint Meetup  
Topic: Animation for Effective Data Visualization with R   
Location: Chicago, IL  
Date: July 24, 2019  
[Video](https://youtu.be/KWECmB0LUqU)    
Links: https://github.com/skirmer/animating_dataviz    

<BR>

#### Event: REV 2  
Topic: Elasticsearch End User Workflows in R and Python   
Location: New York, NY  
Date: May 23, 2019  
[Video](https://dominodatalab.wistia.com/medias/i0f5by0f4q)  
Links: https://github.com/skirmer/elastic_analytics    
[Listen to my conversation with Eric Kavanagh on Inside Analytics podcast](https://insideanalysis.com/insights-from-domino-data-labs-2019-rev2-conference/)  

<BR>

#### Event: satRday Chicago  
Topic: Keynote: What Data Science Can Learn From Sociology  
Location: Chicago, IL  
Date: April 27, 2019   
[Video](https://www.youtube.com/watch?v=quFhQvizBE8&feature=youtu.be&t=1095)    
Links: https://github.com/skirmer/satRdays_chicago_2019  

<BR>

#### Event: R Package Building Workshop  
Topic: 1 day seminar for women and nonbinary folks  
Location: Chicago, IL  
Date: February 23, 2019  
Links: https://github.com/skirmer/r_packages  

<BR>

#### Event: EARL Roadshow Seattle 2018  
Topic: R Packages for Team Collaboration  
Location: Seattle, WA  
Date: November 7, 2018    
Links: https://github.com/skirmer/team_collab 

<BR>

#### Event: ODSC East 2018  
Topic: R Packages for Team Collaboration  
Location: Boston, MA  
Date: May 3, 2018    
Links: https://github.com/skirmer/team_collab  

<BR>

#### Event: Metis Speaker Series  
Topic: R Packages for Team Collaboration  
Location: Chicago, IL  
Date: April 2018    
Links: https://github.com/skirmer/team_collab  

<BR>

#### Partially Derivative Podcast   
May 9, 2017   
http://partiallyderivative.com/podcast/2017/05/09/data-science-near-you  


</font>
<br><BR>
<font size = 2> Looking for a speaker? Contact me at stephanie@stephaniekirmer.com. 


<BR> [Kaggle](http://www.kaggle.com/skirmer) | [Twitter](https://twitter.com/data_stephanie) | [Github](http://github.com/skirmer) | [Linkedin](http://linkedin.com/in/skirmer)

</font>
