[project]
name = "hugo_site"
version = "0.1.0"
description = "Env management for hugo"
authors = [{ name = "Stephanie Kirmer" }]
requires-python = ">=3.9,<4"
license = "Proprietary"
dependencies = [
    "numpy>=1.25.0,<2",
    "feedparser>=6.0.10,<7",
    "mdutils>=1.6.0,<2",
    "beautifulsoup4>=4.12.2,<5",
    "markdownify>=0.14.1,<0.15",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "pytest>=7.3.2,<8",
    "coverage>=7.2.7,<8",
    "flake8>=6.0.0,<7",
    "flake8-bugbear>=23.6.5,<24",
    "black>=24.3.0,<25",
]
